<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="15821" started-at="2019-04-15T13:30:53Z" finished-at="2019-04-15T13:31:09Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="15821" started-at="2019-04-15T13:30:53Z" finished-at="2019-04-15T13:31:09Z">
      <class name="com.fb.test.registerTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.fb.test.registerTest@5e3a8624]" name="setup" is-config="true" duration-ms="7250" started-at="2019-04-15T13:30:53Z" finished-at="2019-04-15T13:31:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="registration()[pri:0, instance:com.fb.test.registerTest@5e3a8624]" name="registration" duration-ms="2410" started-at="2019-04-15T13:31:00Z" finished-at="2019-04-15T13:31:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registration -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.fb.test.registerTest@5e3a8624]" name="teardown" is-config="true" duration-ms="0" started-at="2019-04-15T13:31:03Z" finished-at="2019-04-15T13:31:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.fb.test.registerTest@5e3a8624]" name="setup" is-config="true" duration-ms="5685" started-at="2019-04-15T13:31:03Z" finished-at="2019-04-15T13:31:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="verifytitle()[pri:0, instance:com.fb.test.registerTest@5e3a8624]" name="verifytitle" duration-ms="429" started-at="2019-04-15T13:31:09Z" finished-at="2019-04-15T13:31:09Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Facebook Log In or Sign Up] but found [Facebook - Log In or Sign Up]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Facebook Log In or Sign Up] but found [Facebook - Log In or Sign Up]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.fb.test.registerTest.verifytitle(registerTest.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifytitle -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.fb.test.registerTest@5e3a8624]" name="teardown" is-config="true" duration-ms="0" started-at="2019-04-15T13:31:09Z" finished-at="2019-04-15T13:31:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.fb.test.registerTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
